apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: default-crt
spec:
  secretName: default-crt
  dnsNames:
  - example.io
  - www.example.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - example.io
      - www.example.io
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
